package Proyecto_Estructuras2;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


/**
 * Clase que genera una segunda interfaz del sistema, diseñada para facilitar la búsqueda 
 * y recuperación de información sobre los resumenes. Actúa como un controlador que gestiona 
 * las consultas del usuario interactuando con las estructuras de datos (Tabla Hash y Árboles AVL),
 * permitiendo filtrar el catálogo de resumenes por título, autor o palabras clave.
 *
 * @author Rafael Álvarez, Miguel Sulbarán
 * @version 1.0
 */
public class Ventana2 extends javax.swing.JFrame {    
    
    private TablitaHash tablaTitulos;
    private ArbolAVL arbolAutores;
    private ArbolAVL arbolPalabras;
    
   /**
     * Constructor de la Ventana de Búsqueda
     * 
     * Inicializa la interfaz integrando las estructuras de datos principales 
     * (Tabla Hash y Árboles AVL) provenientes de la ventana anterior, Además,
     * configura la visualización inicial centrada en pantalla y ejecuta 
     * la carga automática de los listados de autores y palabras clave.
     * 
     * @param t Referenceia a la Tabla Hash de títulos para realizar búsquedas exactas.
     * @param a Referencia al Árbol AVL de autores para poblar el filtro de autores.
     * @param p Referencia al Árbol AVL de palabras clave para poblar el filtro de palabras.
     */
    public Ventana2(TablitaHash t, ArbolAVL a, ArbolAVL p) {
        initComponents();
        
        this.tablaTitulos = t;
        this.arbolAutores = a;
        this.arbolPalabras = p;
        
        this.setLocationRelativeTo(null);     
        
        CargarAutoresVentana();
        CargarPalabrasVentana();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Boton_Volver = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Buscar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        Busqueda_titulo = new javax.swing.JButton();
        busqueda_autor = new javax.swing.JButton();
        busqueda_palclav = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        resultados_de_busqueda = new javax.swing.JTextArea();
        Limpiar_Texto = new javax.swing.JButton();
        Salir_del_programa = new javax.swing.JButton();
        ListaAutores = new javax.swing.JComboBox<>();
        ListaPalabras = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Boton_Volver.setText("Volver");
        Boton_Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_VolverActionPerformed(evt);
            }
        });
        jPanel1.add(Boton_Volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, -1, -1));

        jLabel2.setFont(new java.awt.Font("Sitka Text", 0, 24)); // NOI18N
        jLabel2.setText("Busqueda Mediante Filtros:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, -1, -1));

        Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarActionPerformed(evt);
            }
        });
        jPanel1.add(Buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 190, -1));

        jLabel1.setText("Selecciona el autor que deseas buscar:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 90, -1, -1));

        Busqueda_titulo.setText("Titulo");
        Busqueda_titulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Busqueda_tituloActionPerformed(evt);
            }
        });
        jPanel1.add(Busqueda_titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 70, -1));

        busqueda_autor.setText("Autor");
        busqueda_autor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                busqueda_autorActionPerformed(evt);
            }
        });
        jPanel1.add(busqueda_autor, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 150, 70, -1));

        busqueda_palclav.setText("Palabras Clave");
        busqueda_palclav.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                busqueda_palclavActionPerformed(evt);
            }
        });
        jPanel1.add(busqueda_palclav, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, 120, -1));

        jLabel3.setText("A continuación selecciona el tipo de filtro para aplicar:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, -1, -1));

        resultados_de_busqueda.setColumns(20);
        resultados_de_busqueda.setLineWrap(true);
        resultados_de_busqueda.setRows(5);
        resultados_de_busqueda.setWrapStyleWord(true);
        jScrollPane1.setViewportView(resultados_de_busqueda);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 730, 190));

        Limpiar_Texto.setText("Limpiar");
        Limpiar_Texto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Limpiar_TextoActionPerformed(evt);
            }
        });
        jPanel1.add(Limpiar_Texto, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 390, -1, -1));

        Salir_del_programa.setText("Guardar y Salir");
        Salir_del_programa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Salir_del_programaActionPerformed(evt);
            }
        });
        jPanel1.add(Salir_del_programa, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 390, -1, -1));

        ListaAutores.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ListaAutores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListaAutoresActionPerformed(evt);
            }
        });
        jPanel1.add(ListaAutores, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 110, 170, -1));

        ListaPalabras.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ListaPalabras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListaPalabrasActionPerformed(evt);
            }
        });
        jPanel1.add(ListaPalabras, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, 170, -1));

        jLabel4.setText("Ingresa el título que deseas buscar:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabel5.setText("Selecciona la palabra clave que deseas buscar:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 790, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Acción de Boton Volver
     * 
     * Regresa a la pantalla principal. Crea una nueva instancia de la Ventana 1
     * pasándole las estructuras de datos actuales para no perder la información
     * y cierra esta ventana.
     * 
     * @param evt Evento del clic.
     */
    private void Boton_VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_VolverActionPerformed
        Ventana1 v1 = new Ventana1(this.tablaTitulos, this.arbolAutores, this.arbolPalabras);
        v1.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_Boton_VolverActionPerformed

    /**
     * Botón Busqueda titulo
     * 
     * Realiza la búsqueda de una investigación específica usando su título exacto. 
     * Toma el texto ingresado, verifica que no esté vacío y consulta la Tabla Hash; 
     * si encuentra el resumen, muestra su información (autores, palabras clave y contenido) 
     * en el área de resultados, o de lo contrario notifica al usuario que no hay coincidencias.
     * 
     * @param evt Evento del clic.
     */
    private void Busqueda_tituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Busqueda_tituloActionPerformed
       String tituloBuscado = Buscar.getText().trim();
       
       if (tituloBuscado.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Se debe ingresar un título primero.");
        return;
      }
        Resumen encontrado = this.tablaTitulos.Buscar(tituloBuscado);
        
        resultados_de_busqueda.setText("");
        if (encontrado != null) {
        resultados_de_busqueda.append("-REPORTE DE INVESTIGACIÓN \n\n");
        resultados_de_busqueda.append("-Título: " + encontrado.titulo + "\n\n");
        resultados_de_busqueda.append("-Autores: " + encontrado.autores + "\n\n");
        resultados_de_busqueda.append("-Palabras Clave: " + encontrado.palabrasclaves + "\n\n");        
        resultados_de_busqueda.append("-R:\n\n" + encontrado.resumen + "\n");
        Buscar.setText("");     
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "No se pudo encontrar ningún resumen con ese título exacto.");
        Buscar.setText("");        
    }      
    }//GEN-LAST:event_Busqueda_tituloActionPerformed

    /**
     * Botón Limpiar Texto
     * 
     * Borra el contenido actual del área de resultados. Establece el campo de texto 
     * en blanco para limpiar la pantalla y permitir al usuario visualizar nuevas 
     * consultas de forma ordenada.
     * 
     * @param evt Evento del clic.
     */
    private void Limpiar_TextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Limpiar_TextoActionPerformed
        resultados_de_busqueda.setText("");
    }//GEN-LAST:event_Limpiar_TextoActionPerformed

    /**
     * Botón Salir del Programa
     * 
     * Cierra la aplicación. Antes de finalizar, guarda automáticamente 
     * toda la información en el archivo de texto, confirma al usuario que los datos 
     * se han almacenado correctamente y detiene la ejecución.
     * 
     * @param evt Evento del clic.
     */
    private void Salir_del_programaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Salir_del_programaActionPerformed
    this.tablaTitulos.GuardarArchivo("resumenes.txt");

    javax.swing.JOptionPane.showMessageDialog(this, "Datos guardados exitosamente.");
    System.exit(0); 
    }//GEN-LAST:event_Salir_del_programaActionPerformed

    /**
     * Acción del botón Búsqueda PalClav
     * 
     * Toma la palabra calve seleccionada de la lista desplegable y verifica que sea válida. 
     * Luego, consulta el Árbol AVL de palabras clave para recuperar todos los resúmenes 
     * asociados a ese tema y los envía a mostrar en el área de resultados.
     * 
     * @param evt Evento del clic.
     */
    private void busqueda_palclavActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_busqueda_palclavActionPerformed
    String palabra = (String) ListaPalabras.getSelectedItem();
    
    if (palabra == null || palabra.trim().length() == 0) {
        javax.swing.JOptionPane.showMessageDialog(this, "Debes seleccionar una palabra clave en la lista desplegable.");
        return;
    }

    Lista resultados = this.arbolPalabras.Buscar(palabra);
    mostrarListaResultados(resultados, "Palabra Clave");
    }//GEN-LAST:event_busqueda_palclavActionPerformed

    /**
     * Acción del botón Búsqueda Autor
     * 
     * Obtiene el autor seleccionado del menú desplegable y valida que no esté vacío. 
     * Luego, consulta el Árbol AVL de autores para encontrar todas las investigaciones 
     * relacionadas y las envía a mostrar en la sección de resultados.
     * 
     * @param evt Evento del clic.
     */
    private void busqueda_autorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_busqueda_autorActionPerformed
        String autor = (String) ListaAutores.getSelectedItem();

        if (autor == null || autor.trim().length() == 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "Debes seleccionar un autor en la lista desplegable.");
            return;
        }

        Lista resultados = this.arbolAutores.Buscar(autor);
        mostrarListaResultados(resultados, "Autor");
    }//GEN-LAST:event_busqueda_autorActionPerformed

    private void ListaAutoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListaAutoresActionPerformed

    }//GEN-LAST:event_ListaAutoresActionPerformed

    private void BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BuscarActionPerformed

    private void ListaPalabrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListaPalabrasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ListaPalabrasActionPerformed
    
    /**
     * Método mostrarListaResultados
     * 
     * Muestra en el área de texto todos los resúmenes contenidos
     * en la lista resultado de una búsqueda, indicando el tipo de filtro.
     *
     * @param lista       lista de resúmenes a mostrar.
     * @param tipoBusqueda texto descriptivo del filtro aplicado (autor, palabra clave, etc).
     */
    private void mostrarListaResultados(Lista lista, String tipoBusqueda) {
    resultados_de_busqueda.setText("");
    
    if (lista != null && !lista.EsVacio()) {
        resultados_de_busqueda.append("Rresultados por " + tipoBusqueda.toUpperCase() + "\n\n");
        resultados_de_busqueda.append("-Total de resumenes encontrados: " + lista.Tamano() + "\n\n");
        
        NodoLista aux = lista.pFirst;
        
        int contador = 1;
        while (aux != null) {
            Resumen r = aux.data;
            
            resultados_de_busqueda.append("\n-Resumen N°" + contador + "\n\n");
            resultados_de_busqueda.append("-Título: " + r.titulo + "\n\n");
            resultados_de_busqueda.append("-Autores: " + r.autores + "\n\n");
            resultados_de_busqueda.append("-Resumen: \n\n" +  r.resumen + "\n\n");
            
            aux = aux.pNext;
            contador++;
            
            Buscar.setText("");
        }
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "No se encontraron investigaciones asociadas.");
        
        Buscar.setText("");
    }
}   

    
    /**
    * Método CargarAutoresVentana
    * 
    * Llena el JComboBox con todos los autores almacenados en el árbol
    * de autores, en orden alfabético.
    */
   private void CargarAutoresVentana() {
       String[] autores = this.arbolAutores.ObtenerClavesEnOrden();

       javax.swing.DefaultComboBoxModel<String> modelo = new javax.swing.DefaultComboBoxModel<>();

       int i = 0;
       while (i < autores.length) {
           modelo.addElement(autores[i]);
           i = i + 1;
       }

       ListaAutores.setModel(modelo);
   }
   
   /**
     * Método CargarPalabrasVentana
     * 
     * Llena el JComboBox con todas las palabras clave almacenadas en el
     * árbol de palabras, en orden alfabético.
     */
    private void CargarPalabrasVentana() {
        if (this.arbolPalabras == null) {
            return;
        }

        String[] palabras = this.arbolPalabras.ObtenerClavesEnOrden();
        
        javax.swing.DefaultComboBoxModel<String> modelo = new javax.swing.DefaultComboBoxModel<>();

        int i = 0;
        while (i < palabras.length) {
            modelo.addElement(palabras[i]);
            i = i + 1;
        }

        ListaPalabras.setModel(modelo);
    }
   
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boton_Volver;
    private javax.swing.JTextField Buscar;
    private javax.swing.JButton Busqueda_titulo;
    private javax.swing.JButton Limpiar_Texto;
    private javax.swing.JComboBox<String> ListaAutores;
    private javax.swing.JComboBox<String> ListaPalabras;
    private javax.swing.JButton Salir_del_programa;
    private javax.swing.JButton busqueda_autor;
    private javax.swing.JButton busqueda_palclav;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea resultados_de_busqueda;
    // End of variables declaration//GEN-END:variables
}