/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Proyecto_Estructuras2;

/**
 *
 * @author Rafael Álvarez, Miguel Sulbarán
 */
public class Ventana2 extends javax.swing.JFrame {    
    
    private TablitaHash tablaTitulos;
    private ArbolAVL arbolAutores;
    private ArbolAVL arbolPalabras;
    
   
    public Ventana2(TablitaHash t, ArbolAVL a, ArbolAVL p) {
        initComponents();
        
        this.tablaTitulos = t;
        this.arbolAutores = a;
        this.arbolPalabras = p;
        
        this.setLocationRelativeTo(null);        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Boton_Volver = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Buscar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        Busqueda_titulo = new javax.swing.JButton();
        busqueda_autor = new javax.swing.JButton();
        busqueda_palclav = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        resultados_de_busqueda = new javax.swing.JTextArea();
        Limpiar_Texto = new javax.swing.JButton();
        Salir_del_programa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Boton_Volver.setText("Volver");
        Boton_Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_VolverActionPerformed(evt);
            }
        });
        jPanel1.add(Boton_Volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, -1, -1));

        jLabel2.setFont(new java.awt.Font("Sitka Text", 0, 24)); // NOI18N
        jLabel2.setText("Busqueda Mediante Filtros:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, -1, -1));
        jPanel1.add(Buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 80, 210, -1));

        jLabel1.setText("A continuacion ingresa la palabra que deseas buscar:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        Busqueda_titulo.setText("Titulo");
        Busqueda_titulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Busqueda_tituloActionPerformed(evt);
            }
        });
        jPanel1.add(Busqueda_titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, -1, -1));

        busqueda_autor.setText("Autor");
        busqueda_autor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                busqueda_autorActionPerformed(evt);
            }
        });
        jPanel1.add(busqueda_autor, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 130, -1, -1));

        busqueda_palclav.setText("Palabras Clave");
        busqueda_palclav.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                busqueda_palclavActionPerformed(evt);
            }
        });
        jPanel1.add(busqueda_palclav, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 130, -1, -1));

        jLabel3.setText("Selecciona el tipo de filtro de que deseas aplicar:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        resultados_de_busqueda.setColumns(20);
        resultados_de_busqueda.setLineWrap(true);
        resultados_de_busqueda.setRows(5);
        resultados_de_busqueda.setWrapStyleWord(true);
        jScrollPane1.setViewportView(resultados_de_busqueda);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 570, 190));

        Limpiar_Texto.setText("Limpiar");
        Limpiar_Texto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Limpiar_TextoActionPerformed(evt);
            }
        });
        jPanel1.add(Limpiar_Texto, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 380, -1, -1));

        Salir_del_programa.setText("Salir");
        Salir_del_programa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Salir_del_programaActionPerformed(evt);
            }
        });
        jPanel1.add(Salir_del_programa, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 380, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 638, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Boton_VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_VolverActionPerformed
        Ventana1 v1 = new Ventana1(this.tablaTitulos, this.arbolAutores, this.arbolPalabras);
        v1.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_Boton_VolverActionPerformed

    private void Busqueda_tituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Busqueda_tituloActionPerformed
       String tituloBuscado = Buscar.getText().trim();
       
       if (tituloBuscado.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Se debe ingrsar un título primero.");
        return;
      }
        Resumen encontrado = this.tablaTitulos.Buscar(tituloBuscado);
        
        resultados_de_busqueda.setText("");
        if (encontrado != null) {
        resultados_de_busqueda.append("-REPORTE DE INVESTIGACIÓN \n\n");
        resultados_de_busqueda.append("-TÍTULO: " + encontrado.titulo + "\n\n");
        resultados_de_busqueda.append("-AUTORES: " + encontrado.autores + "\n\n");
        resultados_de_busqueda.append("-PALABRAS CLAVE: " + encontrado.palabrasclaves + "\n\n");        
        resultados_de_busqueda.append("-RESUMEN:\n\n" + encontrado.resumen + "\n");
        Buscar.setText("");     
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "No se pudo encontrar ningún resumen con ese título exacto.");
        Buscar.setText("");        
    }

    
       
    }//GEN-LAST:event_Busqueda_tituloActionPerformed

    private void Limpiar_TextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Limpiar_TextoActionPerformed
        resultados_de_busqueda.setText("");
    }//GEN-LAST:event_Limpiar_TextoActionPerformed

    private void Salir_del_programaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Salir_del_programaActionPerformed
        this.dispose();
    }//GEN-LAST:event_Salir_del_programaActionPerformed

    private void busqueda_palclavActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_busqueda_palclavActionPerformed
        String palabra = Buscar.getText().trim();
        if (!palabra.isEmpty()) {
            Lista resultados = this.arbolPalabras.Buscar(palabra);
            mostrarListaResultados(resultados, "PALABRA CLAVE");
        }
    }//GEN-LAST:event_busqueda_palclavActionPerformed

    private void busqueda_autorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_busqueda_autorActionPerformed
        String autor = Buscar.getText().trim();
        if (!autor.isEmpty()) {
            Lista resultados = this.arbolAutores.Buscar(autor);
            mostrarListaResultados(resultados, "AUTOR");
        }
    }//GEN-LAST:event_busqueda_autorActionPerformed
    
    
    private void mostrarListaResultados(Lista lista, String tipoBusqueda) {
    resultados_de_busqueda.setText("");
    
    if (lista != null && !lista.EsVacio()) {
        resultados_de_busqueda.append("RESULTADOS POR " + tipoBusqueda.toUpperCase() + "\n\n");
        resultados_de_busqueda.append("-Total de resumenes encontrados: " + lista.Tamano() + "\n\n");
        
        NodoLista aux = lista.pFirst;
        
        int contador = 1;
        while (aux != null) {
            Resumen r = aux.data; // Accedemos al resumen guardado en el nodo
            
            resultados_de_busqueda.append("\n-Resumen N°" + contador + "\n\n");
            resultados_de_busqueda.append("-TÍTULO: " + r.titulo + "\n\n");
            resultados_de_busqueda.append("-AUTORES: " + r.autores + "\n\n");
            resultados_de_busqueda.append("-RESUMEN: \n\n" +  r.resumen + "\n\n");
            
            aux = aux.pNext; // Avanzamos al siguiente nodo
            contador++;
            
            Buscar.setText("");
        }
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "No se encontraron investigaciones asociadas.");
        
        Buscar.setText("");
    }
}   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boton_Volver;
    private javax.swing.JTextField Buscar;
    private javax.swing.JButton Busqueda_titulo;
    private javax.swing.JButton Limpiar_Texto;
    private javax.swing.JButton Salir_del_programa;
    private javax.swing.JButton busqueda_autor;
    private javax.swing.JButton busqueda_palclav;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea resultados_de_busqueda;
    // End of variables declaration//GEN-END:variables
}
